### ISSUE TITLE
Edit product category relation on product view if the product is assigned

### ISSUE THREAD

**Issue by ahrrikis** [akeneo/pim-community-standard#115]
Hi, 
I am facing the problem that I can't edit the category of a product in a category tree, if the product is assigned to one category of  the belonging category tree. 
Javascript Error on the product edit page is: 
 Error: The route "pim_enrich_product_listcategories" requires the parameter "categoryId". http://akeneo/bundles/fosjsrouting/js/router.js

Thanks

**Comment by ahrrikis** [comment]
I figured out it was an caching issue related to upgrading from 1.2 to 1.3.

**Comment by nidup** [comment]
Hi,
Did you encounter any issue during the upgrade 1.2 -> 1.3 ?
We're always interested to get feedback to enhance this process.
Regards

**Comment by ahrrikis** [comment]
It wasnt that hard, as from 1.1 to 1.2.
Just the the changing parameter/variables names, and routes were problematic.

But actually I have to state, the new feature sequantial edit, is awesome.

**Comment by nidup** [comment]
Thank you for the feedback !
