### ISSUE TITLE
 Uncaught exception 'ReflectionException'

### ISSUE THREAD

**Issue by tinuzz** [akeneo/pim-community-standard#117]
After follwing the upgrade procedure here: https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-1.3.md my PIM install is broken, giving the following error direcly after login:

`PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Property Pim\\Bundle\\CatalogBundle\\Entity\\Attribute::$useableAsGridColumn does not exist' in /home/pimuser01/www/pim-community-standard-v1.2.11-icecat/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:82\nStack trace:\n#0 /home/pimuser01/www/pim-community-standard-v1.2.11-icecat/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(82): ReflectionProperty->__construct('Pim\\\\Bundle\\\\Cata...', 'useableAsGridCo...')\n#1 /home/pimuser01/www/pim-community-standard-v1.2.11-icecat/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(893): Doctrine\\Common\\Persistence\\Mapping\\RuntimeReflectionService->getAccessibleProperty('Pim\\\\Bundle\\\\Cata...', 'useableAsGridCo...')\n#2 /home/pimuser01/www/pim-community-standard-v1.2.11-icecat/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(537): Doctrine\\ORM\\Mapping\\ClassMetadataInfo->wakeupReflection(Object(Doctrine\\Common\\Persis in /home/pimuser01/www/pim-community-standard-v1.2.11-icecat/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php on line 82`

Please note that, as the instructions dictated, I merged the changes from 1.3.0 into my existing 1.2.11 install, the error still shows 1.2.11 in the directory names. 

Perhaps it is worth noting that running `php app/console doctrine:migrations:migrate` resulted in 

`Migrating up to 0 from 0   [Doctrine\DBAL\Migrations\MigrationException]   Could not find any migrations to execute.`

What did I miss? Or are the instructions incomplete?

**Comment by tinuzz** [comment]
BTW, this is a completely standard installation of the Akeneo PIM without any customizations.

**Comment by vbnet3d** [comment]
I have the same error - but this only occurs in production. app_dev.php is functioning properly.

**Comment by vbnet3d** [comment]
This seems to be related to APC settings. Removing the following from config_prod.yml seems to have returned everything to normal:

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver: apc
                result_cache_driver:   apc
                query_cache_driver:    apc

**Comment by sumbobyboys** [comment]
Hi guys,

Sorry for the delay to give you a response. Your problem seems related to cache (as it still refers to the old folder).

Can you run the following commands and tells me if its help ?

```bash
rm -rf ./app/cache/*
sudo service apache restart
```

**Comment by tinuzz** [comment]
Julien Sanchez schreef op 2-3-2015 om 23:53:
> Hi guys,
> 
> Sorry for the delay to give you a response. Your problem seems related
> to cache (as it still refers to the old folder).
> 
> Can you run the following commands and tells me if its help ?
> 
> rm -rf ./app/cache/*
> sudo service apache restart

This was an evaluation install for a client without any real data.
Instead of trying to fix the upgraded PIM, we did a reinstall with 1.3.
The old install is gone, so I cannot check the potential fix anymore I'm
afraid.

Best regards,
Martijn.
