### ISSUE TITLE
cant install with composer

### ISSUE THREAD

**Issue by thimmey** [akeneo/pim-community-standard#157]
I'm trying to install akeneo and followed the manual for composer install.

during the installation the installer asked me for db driver, db host, db database, db user and db password.

copy of console output
https://gist.github.com/thimmey/51574b22298285c66c95

Html Output without html tags:
https://gist.github.com/thimmey/f8791e5fcdcf174c0ceb

How can i solve this problem?

Many greetings

**Comment by sumbobyboys** [comment]
Hello @thimmey,

Can you give us more informations about your environment and context. Particularly, the html in your terminal is not normal.

About your question: at the end of the composer install command, we run incenteev to create the `app/parameters.yml` file. You can leave the default values during the composer install command and edit them later. 

Regards, 

Julien

**Comment by thimmey** [comment]
Hi Julien,

the system is running php 5.5 and MySQL 5.5. Its a hosting provider, i dont know what OS is running.

Regards

**Comment by thimmey** [comment]
Hi Julien, i found out it was a php configuration Problem. I had to set register_argc_argv=On
