### ISSUE TITLE
Datebasesetup not loaded?

### ISSUE THREAD

**Issue by thimmey** [akeneo/pim-community-standard#158]
Hello,

sofar i downloaded akeneo via composer from github. 
I also entered the following db informations in the app/config/parameters.yml
parameters:
    database_driver: pdo_mysql
    database_host: db12345.mydbserver.com
    database_port: 3306
    database_name: usr_p12345_1
    database_user: p12345
    database_password: 'password12345#'
    locale: en
    secret: 'secret12345#'

Now I try to install it with the folowing command:
"php app/console pim:install --env=prod" 

which is returning the following error:
Prepare database schema (driver: doctrine/orm)
 Database does not exist yet
Could not create database for connection named `usr_p12345_1`
SQLSTATE[HY000] [1045] Access denied for user 'p12345'@'172.17.33.167' (using password: YES)
The command terminated with an error code: 1.
 [Exception]
  The command terminated with an error code: 1.

When i try to connect with the mysql cli client it works. No Acces denied Error.

Many greetings

**Comment by sumbobyboys** [comment]
Hello @thimmey,

Did you try to remove the `'` around the database password ?

Regards,

Julien
