### ISSUE TITLE
How to interval/cronjoby import profiles/jobs?

### ISSUE THREAD

**Issue by linslin** [akeneo/pim-community-standard#160]
I did not found informations about automatization of a import profile. For example, I want to run a category import every night or tow times a day. Receive reports about fails or success via Mail would also be nice. How to do this with Akeneo?

**Comment by sumbobyboys** [comment]
Hello @linslin,

You can run a batch job by running the following command:

```bash
$ app/console akeneo:batch:job my_job_profile
```

You can also inject specific configuration with the `-c` argument and use a cron job to run it every night.

Regards,

Julien

**Comment by linslin** [comment]
Thanks for your answer. Thought there is a way to do this via the UI. So, lets have a cronjob. :+1:
