### ISSUE TITLE
Wrong feature teasing in user documentation

### ISSUE THREAD

**Issue by linslin** [akeneo/pim-community-standard#162]
Hey Guys,

we run into that: 
http://www.akeneo.com/doc/user-guide/searching-products/quick-search/

So .. we searched for the "quick search" in our application. After some time we found this post: 
http://www.akeneo.com/forums/topic/searching-for-products/

Search is not supported anymore. Please remove this feature so other user will not run into that.

Cheers
Lin

**Comment by fred2gombert** [comment]
Hey linslin!

You're right! Thank you - we just removed this entry from the user guide. 

BTW we will release very soon a more complete user guide so stay tuned ;)

**Comment by linslin** [comment]
Thanks @fred2gombert. Btw. is there a way to enable the search again + will the search integrated soon? Its hard for us to find a specific product in more than 100.000 Products.
