### ISSUE TITLE
Why is the asset bundle not installed in the install routine

### ISSUE THREAD

**Issue by linslin** [akeneo/pim-community-standard#165]
Every time I Install Akeneo new on a system I have to run:

`php app/console pim:installer:assets`

Why is the assets not generated in the install script. Iam using community-standards 1.3.17

**Comment by sumbobyboys** [comment]
Hi @linslin,

The install process `app/console pim:install --force` runs `app/console pim:install:db` and `app/console pim:install:asset` so you should not have to re-run the second command.

Regards,

julien

**Comment by linslin** [comment]
Thanks! So this information is missing in the readme. https://github.com/akeneo/pim-community-standard

Cheers
