### ISSUE TITLE
Documentation deprecated 

### ISSUE THREAD

**Issue by linslin** [akeneo/pim-community-standard#167]
Hey guys,

another Error found in your Documentation @Generating a clean database

PimInstallBundle is not located in `app/config/parameters.yml` its located in `app/config/pim_parameters.yml:`

Cheers

**Comment by akkermanronald** [comment]
Has always worked in app/config/parameters.yml ?

**Comment by jmleroux** [comment]
It is not an error : `app/config/parameters.yml` should be present on your system as your personnal configuration file. It is ignored by git and overwrite the `pim_parameters.yml`

You can initialize it by copying `parmeters_dist.yml`.

Regards,
JM
