### ISSUE TITLE
Upgrade scripts for 1.4 not in tags 1.4.0 and 1.4.1

### ISSUE THREAD

**Issue by bartdelvauxx** [akeneo/pim-community-standard#189]
I am trying to upgrade version 1.3 to 1.4. I dit the required things to update the files to the latest version. 

But when I look into the code, I see that the folder upgrades/1.3-1.4 is missing. This folder is only available in the master branch and 1.4 branch but not on the tags which are used with the composer installer. 

Also these files are missing in the archive that could be downloaded from the website.

**Comment by jmleroux** [comment]
Hi @bartdelvauxx ,

Thanks for your report. 
This issue has been identified and the upgrades will be present in the next coming patch.

**Comment by jmleroux** [comment]
Corresponding PR : #188
