### ISSUE TITLE
new patch available message

### ISSUE THREAD

**Issue by akkermanronald** [akeneo/pim-community-standard#200]
See screenshot from a fresh 1.4 install (using composer).

<img width="445" alt="schermafbeelding 2015-10-11 om 12 31 35" src="https://cloud.githubusercontent.com/assets/15016164/10416354/284d4502-7014-11e5-84a4-29999a473be5.png">

**Comment by akkermanronald** [comment]
Message disappeared after re-installing with demo data.

**Comment by jmleroux** [comment]
Hello,

This is a known bug in versions comparison which will be fixed soon, plus the fact that the version checker server takes some time to be up to date.

Thanks for the feedback,

JM

**Comment by jmleroux** [comment]
For the record, [PIM-4925](https://github.com/akeneo/pim-community-dev/pull/3339) will be reopened.
