### ISSUE TITLE
currency

### ISSUE THREAD

**Issue by akkermanronald** [akeneo/pim-community-standard#208]
If we disable USD as currency and only add EUR to a channel, we should not see a USD field on attributes of the type price? See below error which occurs when trying to save a price entered into the USD field of a price attribute.

<img width="688" alt="schermafdruk 2015-10-21 11 10 59" src="https://cloud.githubusercontent.com/assets/15016164/10632433/bb4f5570-77e4-11e5-89e1-69b97a9b5902.png">

**Comment by akkermanronald** [comment]
Issue solved after logging out and logging back in.

**Comment by jmleroux** [comment]
thx for the feedback, it's a pleasure to have active community members.

:+1:
