### ISSUE TITLE
Doctrine migrations broken

### ISSUE THREAD

**Issue by marcobamert** [akeneo/pim-community-standard#209]
When using a clean installation of the latest version 1.4.4 the migrations seem to be broken:

```
php app/console doctrine:migrations:status
```

The output shows that 6 new migrations are available:
```
vagrant@demo:/var/www/demo.akeneo.dev$ php app/console doctrine:migrations:status

 == Configuration

    >> Name:                                               PIM Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Name:                                      akeneo_pim
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 migration_versions
    >> Migrations Namespace:                               Pim\Upgrade\Schema
    >> Migrations Directory:                               /var/www/demo.akeneo.dev/app/../upgrades/schema
    >> Previous Version:                                   Already at first version
    >> Current Version:                                    0
    >> Next Version:                                       _1_4-_2-01 50:51:21 (_1_4_20150512133600_pim_session)
    >> Latest Version:                                     _1_4-_2-01 50:92:21 (_1_4_20150922153325_versioning)
    >> Executed Migrations:                                0
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               6
    >> New Migrations:                                     6
```

However, trying to apply them with `php app/console doctrine:migrations:migrate` fails at `_1_4_20150512133600_pim_session` with

```
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'pim_session' already exists
```

**Comment by jmleroux** [comment]
why do you use migrations on a new installation ?

**Comment by marcobamert** [comment]
That was only for testing reasons after applying migrations on a existing project failed with the same error. Also, a new installation should not offer migrations at all - the pim:install command should take care of applying the up-to-date schema right?

**Comment by jmleroux** [comment]
> the pim:install command should take care of applying the up-to-date schema right

Totally exact, you don't need the run the migrations

**Comment by marcobamert** [comment]
Hi Jean-Marie
Can you give me an update on this? Is it on your roadmap? It currently means that new projects started with 1.4.x will no be able to apply migrations in later deployments.

Thanks,
Marco
