### ISSUE TITLE
How to add a locale?

### ISSUE THREAD

**Issue by kristiaanvandeneynde** [akeneo/pim-community-standard#220]
I want to add a locale en_001 for "English (World)", but can only find a list of locales in src/Pim/Bundle/InstallerBundle/Resources/config/locales. Is that the right place to add a new locale and if so, how would Akeneo know to apply the "English (World)" label?

**Comment by saulhudson** [comment]
I have exactly the same requirement!

We sell our products on multiple websites (all UK English based sites) and we require product descriptions to be unique to the site. The Locale system seems perfect for just this task but I'd like to add our own along the lines of "en_brand_awesome_site_1", "en_brand_awesome_site_2" etc.

**Comment by saulhudson** [comment]
I have tried adding a locale into the file you mentioned but it doesn't appear in the software itself. Did you have any success with this?

**Comment by saulhudson** [comment]
See also http://www.akeneo.com/forums/topic/how-can-i-update-the-locale-code/#post-6452

Same question, currently no solution

**Comment by LaureBro** [comment]
Hello, 

@kristiaanvandeneynde: you can add new locales in the directory you mentioned but if it has to be done before installation, if it is changed after install, you need to edit it directly in your database.

@saulhudson, if you have 2 websites using the same English description, you should have one locale for instance "en_US", and 2 channels: site1 and site 2, and make your description attribute as "scopable".
You'll be able to export one unique English description for each website. 

Does it make sense to you?

**Comment by saulhudson** [comment]
@LaureBro Thanks for your suggestion that makes perfect sense and seems to work exactly how I was hoping it would. Thank you very much!
