### ISSUE TITLE
fatal error after upgrade to 1.4.11

### ISSUE THREAD

**Issue by akkermanronald** [akeneo/pim-community-standard#234]
See below, just doing a composer update from 1.4.10 to 1.4.11
Solution needed a.s.a.p. as this is our production environment. 

![schermafdruk 2015-11-27 13 07 18](https://cloud.githubusercontent.com/assets/15016164/11441036/662a2f16-9508-11e5-97c5-0c7cb886e064.png)

**Comment by akkermanronald** [comment]
We have managed to restore a snapshot of our server to previous state. Please confirm when this upgrade can be carried out safely, without above mentioned error.

**Comment by nidup** [comment]
Did you refresh your prod cache once the patch applied ?

**Comment by akkermanronald** [comment]
Hi,

Yes, that's exactly what triggers the error. We also completely cleared the cache with rm -rf.  But also after complete clearance the error remains when clearing prod cache and application remains server error 500.

Regards
Ronald

**Comment by damien-carcel** [comment]
Hello Ronald.

I encountered the same error as you. However, completely removing the cache with "rm -rf" then running "app/console --env=prod cache:clear" did make the problem disappear for me.

Regards,
Damien

**Comment by akkermanronald** [comment]
Great, we will give it another go in that case!

**Comment by akkermanronald** [comment]
We have now succesfully updated. Whilst researching the error (which happened again on a new attempt) we noticed that the dev and prod subfolders in app/cache had not been removed, despite using the sudo rm -rf /app/cache command:

<img width="410" alt="schermafdruk 2015-12-01 09 59 21" src="https://cloud.githubusercontent.com/assets/15016164/11496541/e5228806-9812-11e5-9309-971d317b3ef6.png">

**Comment by nidup** [comment]
Good news, thank you for the feedback
