### ISSUE TITLE
Parent product within a variant group

### ISSUE THREAD

**Issue by saulhudson** [akeneo/pim-community-standard#241]
Maybe I've missed something obvious but is it possible to define a "parent" product within a variant group? My requirement is to provide a canonical parent for each group to prevent duplicate content on product pages on our eCommerce sites.

**Comment by LaureBro** [comment]
Hello, 

No it is not possible to define a parent product within the variant groups. A solution could be to create a new product, the "parent product", within the PIM (along with the other products) and associate this product to its children products.

For the Enterprise Edition users, you can manage parent products with the Inner Variation Bundle. 

Best regards, 

Laure

**Comment by saulhudson** [comment]
Thank you very much for you advice.
