### ISSUE TITLE
ProductValueInterface setAttribute() not found

### ISSUE THREAD

**Issue by jcandan** [akeneo/pim-community-standard#96]
In the **How to Create a Specific Connector** documentation, under [Create Our Processor](http://docs.akeneo.com/1.0/cookbook/import_export/create-specific-connector.html#create-our-processor), in the code example provided it instructs us to use the `setAttribute()` function from the `ProductValueInterface`.

```
...
     if (!$product) {
            $product = $this->productManager->createProduct();
            $value   = $this->productManager->createProductValue();
            $value->setAttribute($attribute);
            $value->setData($sku);
            $product->addValue($value);
            $this->stepExecution->incrementSummaryInfo('create');

            return $product;

        } else {
...
```

However, this has not been pulled into **pim-community-standard** from **[pim-community-dev](https://github.com/akeneo/pim-community-dev/blob/76fac9458d1be58aee50897c85f06b31cc9806a0/src/Pim/Bundle/CatalogBundle/Model/ProductValueInterface.php)** yet. Please advise.

**Comment by sumbobyboys** [comment]
Hello @jcandan,

Thank you for your feedback.
Pim community standard is only an empty project which depends on pim community dev. So the only difference between the two projects is that bundles contained in the src folder are in the vendor's folder in the standard edition.

The setAttribute method is not in the interface in 1.2 but will be available in 1.3 (https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Model/ProductValueInterface.php#L82).

Regards
